version: '3.2'
services:
  egg-server:
    container_name: egg-server
    # image: postgres:11.8
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    ports:
      - 7001:7001
    command: |
      npm run start
