name: Test

on:
  push

jobs:
  build-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout server code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/qiangqiangtech/xyy-backend
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/qiangqiangtech/xyy-backend:master