name: Test

on: push

jobs:
  build-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 43.143.101.114
          username: root
          password: ${{ secrets.SEVER_PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            sh /tmp/start.sh
