name: Test

on: push

jobs:
  build-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 43.143.101.114
          username: root
          password: ${{ secrets.SEVER_PASSWORD }}
          port: 22
          command_timeout: 30m
          script: |
            cd /root/
            rm -rf xu-yi-yang-back
            git clone https://github.com/qianggechao/xu-yi-yang-back.git
            cd /root/xu-yi-yang-back
            touch .env
            echo "MONGO_USERNAME=${{ env.USERNAME }}" >> .env
            echo "MONGO_PASSWORD=${{ env.PASSWORD }}" >> .env
            npm i
            npm stop
            npm run tsc
            npm start
